### ISSUE TITLE
Neighborhood Maps Seem to be broken

### ISSUE THREAD

**Issue by iamhunter** [PhillipBost/durham-hoods-geojson#10]
Hey there!

So my real estate agent recommended that we use Durham Hoods to scope out the area, but it looks like the neighborhood data is broken - "A map will appear here."
![image](https://user-images.githubusercontent.com/12401866/182975347-30a42fb5-c6c3-4372-b948-50d3168e4f72.png)

Anyways, not sure if it's still maintained at all or if you'll get this, or if this is the right place, but just wanted to let you know.  Also if you need a hand with maintenance, let me know.

Thanks!

**Comment by PhillipBost** [comment]
Hi Hunter, thanks for this note!
I'm actually shocked to see durhamhoods.com still live considering I sold the domain many years ago and have not kept the project going. Whoever bought the domain (I can't even remember now) must've valued the idea of the map having a home even if they didn't plan to keep it updated. Considering the fact that the map still exists here on github and (in my opinion) a much more superior resource that I contributed to minorly called the Durham Neighborhood Compass, I had no issues walking away from the domain when I did.
Hopefully you'll find the following resource more helpful. The map can be segmented into blockgroups or neighborhoods (as I drew them about a decade ago). Here is the Omah St neighborhood as a starting point:
https://compass.durhamnc.gov/en/compass/LUDIV/blockgroup?selectGroupName=Omah%20Street&selectGroupType=Neighborhood
